
// This file has been generated by the GUI designer. Do not modify.
namespace NXTCamView.Gtk.Widgets
{
	public partial class StretchyImage
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.Image image;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NXTCamView.Gtk.Widgets.StretchyImage
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NXTCamView.Gtk.Widgets.StretchyImage";
			// Container child NXTCamView.Gtk.Widgets.StretchyImage.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.image = new global::Gtk.Image ();
			this.image.Name = "image";
			w1.Add (this.image);
			this.scrolledwindow1.Add (w1);
			this.Add (this.scrolledwindow1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.image.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnImageExposeEvent);
		}
	}
}
