
// This file has been generated by the GUI designer. Do not modify.
namespace NXTCamView.Gtk.Windows
{
	public partial class CaptureWindow
	{
		private global::Gtk.VBox vbox2;
		
		private global::NXTCamView.Gtk.Widgets.StretchyImage stretchyImage;
		
		private global::Gtk.Statusbar statusbar;
		
		private global::Gtk.ProgressBar progressbar;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.CheckButton showIterpolatedCheckbutton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NXTCamView.Gtk.Windows.CaptureWindow
			this.Name = "NXTCamView.Gtk.Windows.CaptureWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("CaptureWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child NXTCamView.Gtk.Windows.CaptureWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.stretchyImage = new global::NXTCamView.Gtk.Widgets.StretchyImage ();
			this.stretchyImage.Events = ((global::Gdk.EventMask)(256));
			this.stretchyImage.Name = "stretchyImage";
			this.vbox2.Add (this.stretchyImage);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.stretchyImage]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.statusbar = new global::Gtk.Statusbar ();
			this.statusbar.Name = "statusbar";
			this.statusbar.Spacing = 6;
			// Container child statusbar.Gtk.Box+BoxChild
			this.progressbar = new global::Gtk.ProgressBar ();
			this.progressbar.WidthRequest = 1;
			this.progressbar.Name = "progressbar";
			this.statusbar.Add (this.progressbar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.statusbar [this.progressbar]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 2;
			this.vbox2.Add (this.statusbar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.statusbar]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.showIterpolatedCheckbutton = new global::Gtk.CheckButton ();
			this.showIterpolatedCheckbutton.CanFocus = true;
			this.showIterpolatedCheckbutton.Name = "showIterpolatedCheckbutton";
			this.showIterpolatedCheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Interpolated");
			this.showIterpolatedCheckbutton.DrawIndicator = true;
			this.showIterpolatedCheckbutton.UseUnderline = true;
			this.hbox1.Add (this.showIterpolatedCheckbutton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.showIterpolatedCheckbutton]));
			w4.Position = 0;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 411;
			this.progressbar.Hide ();
			this.Show ();
			this.showIterpolatedCheckbutton.Toggled += new global::System.EventHandler (this.OnShowIterpolatedCheckbuttonToggled);
		}
	}
}
